### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by t170815518** [razorness/vue3-calendar-heatmap#18]
I am pretty new to Vue, and when I followed the instructions to import the component locally:

```
<template>
<CalendarHeatmap></CalendarHeatmap>
</template>
import { CalendarHeatmap } from 'vue3-calendar-heatmap'
export default {
    components: {
        CalendarHeatmap
    },
    // ...
}
```

I got the error `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')`?

Thank you for the help in advance :)

**Comment by razorness** [comment]
Your [SFC](https://vuejs.org/guide/scaling-up/sfc.html#single-file-components) structure should look like this:

```vue
<template>
   // your template stuff
   <CalendarHeatmap></CalendarHeatmap>
</template>

<script>
import { CalendarHeatmap } from 'vue3-calendar-heatmap'
export default {
    components: {
        CalendarHeatmap
    },
    // ...
}
</script>
```

May that's your error.

**Comment by t170815518** [comment]
Thank you very much for the help, @razorness, I missed the required parameters like values and endDate as you pointed out. 

After adding them, the heatmap can be displayed properly. :)
