### ISSUE TITLE
Dates Off by 1 Day

### ISSUE THREAD

**Issue by paltman** [razorness/vue3-calendar-heatmap#24]
My data has string dates (YYYY-MM-DD) however, when fed into component, they are being rendered as one day prior.  Could this be a timezone issue with how the component is handling dates?

<img width="199" alt="Screenshot 2023-04-23 at 8 18 28 AM" src="https://user-images.githubusercontent.com/1192/233842031-fdb4dfd7-762a-482e-99c4-ecb9de81bfc0.png">

<img width="201" alt="Screenshot 2023-04-23 at 8 18 37 AM" src="https://user-images.githubusercontent.com/1192/233842037-55c5cafc-ed67-433f-abb6-dde94b1c92de.png">

**Comment by paltman** [comment]
Seems like a naive parsing of the date string.  I think I can work around it like so:

```javascript
"2023-04-18".valueOf()
// "2023-04-18"

new Date("2023-04-18")
// Date Mon Apr 17 2023 19:00:00 GMT-0500 (Central Daylight Time)

new Date("2023-04-18T00:00:00")
// Date Tue Apr 18 2023 00:00:00 GMT-0500 (Central Daylight Time)
```

**Comment by razorness** [comment]
You can use instance of `Date` and `string` as date field. If your date values don't have any timezone, it will be parsed as local time. You can parse the values on your own and set your Date objects as date values.

Best you can do is to use ISO8601/RFC3339 compliant strings.
