### ISSUE TITLE
bug: empty hover dont detail

### ISSUE THREAD

**Issue by productdevbook** [razorness/vue3-calendar-heatmap#9]
<img width="229" alt="CleanShot 2021-12-01 at 13 55 03@2x" src="https://user-images.githubusercontent.com/38668796/144222166-53463ca8-80bc-44e5-b396-392d9e6394b4.png">

github example
<img width="349" alt="CleanShot 2021-12-01 at 13 56 17@2x" src="https://user-images.githubusercontent.com/38668796/144222209-7f8b6155-1407-42a5-ade2-d7dbf281d927.png">

**Comment by razorness** [comment]
Hi productdevbook! 
Thank you for your contributions. I will take a look into your stuff this weekend.
